# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  
  pod 'Desafio-iOS-Lib', :path => '/Users/rodrigo.goncalves/Documents/Projetos/Testes/desafio-ios-lib/desafio-ios-lib' 

  target 'SampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleAppUITests' do
    # Pods for testing
  end

end
